modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/Pipsqueak737/Opulence/issues"
license = "GPLv3"

[[mods]]
modId = "opulence"
version = "0.1.2"
displayName = "Opulence"
authors = "Pipsqueak737"
description = '''
Adds new decorative variants of expensive blocks like gold, diamond, and emerald!
'''
logoFile = "logo.png"

[[dependencies.opulence]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.opulence]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.opulence]]
    modId = "blueprint"
    mandatory = true
    versionRange = "[1.19.2,)"
    ordering = "BEFORE"
    side = "BOTH"

[modproperties.opulence]
catalogueItemIcon = "opulence:engraved_emerald"